"""create users table

Revision ID: 3561799945aa
Revises: 
Create Date: 2026-07-25 16:55:04.476546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3561799945aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('user_time', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


"""
========================= DOCUMENTAÇÃO DO ARQUIVO =========================
Utilidade:
    PRIMEIRA revisão (migration) do banco: cria a tabela 'users', que
    corresponde ao modelo User de server/database/models.py. É o "commit
    inicial" do schema — foi este arquivo que, ao rodar
    `alembic upgrade head`, criou a tabela dentro do database.db.

    Foi gerado por `alembic revision --autogenerate -m "create users table"`,
    comparando o table_registry.metadata (schema desejado) com o banco
    vazio (schema atual).

Imports:
    - typing.Sequence, Union: apenas para tipar os identificadores de
      revisão (podem ser str, sequência de str ou None).
    - alembic.op: API de operações de schema (create_table, drop_table,
      add_column, ...). É o que gera o DDL apropriado para o dialeto.
    - sqlalchemy as sa: tipos de coluna (sa.Integer, sa.String, sa.Boolean,
      sa.DateTime) e constraints usadas na definição da tabela.

Classes:
    Não há classes definidas neste arquivo.

Variáveis de controle (usadas pelo Alembic):
    - revision = '3561799945aa': identificador desta revisão.
    - down_revision = None: não há revisão anterior -> esta é a base da
      corrente de migrations.
    - branch_labels / depends_on: não usados (recursos de branches).

Funções:
    - upgrade(): aplica a mudança "para frente". Cria a tabela 'users' com
      as colunas user_id, user_email, user_name, user_password, is_ativo,
      is_admin, user_time e created_at, mais a PK em user_id e a constraint
      UNIQUE em user_email. Sem parâmetros; não retorna valor.
      Observação: created_at recebeu
      server_default=sa.text('(CURRENT_TIMESTAMP)') — a tradução do
      func.now() do modelo para o SQL do SQLite (migrations são específicas
      do dialeto).
    - downgrade(): desfaz a mudança, apagando a tabela 'users' com
      op.drop_table. ATENÇÃO: apaga os dados. Sem parâmetros; não retorna
      valor.

Comandos relacionados:
    uv run alembic upgrade head        # executa o upgrade() acima
    uv run alembic downgrade -1        # executa o downgrade() acima
    uv run alembic current             # mostra se o banco está nesta revisão
    Guia completo: migrations/GUIA-ALEMBIC.md
==========================================================================
"""
